#!/bin/bash

set -eu

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 (local|oss)"
  exit 1
fi

docker build -t pivotal-cf-onboarding .
docker run -v "$PWD:/onboarding" -w /onboarding -it pivotal-cf-onboarding go run generate-tracker-csv.go "${1}"

echo -e "\n\nGenerated output CSV at '$PWD/onboarding-tracker.csv'"
