#!/bin/bash
# shellcheck disable=SC2086
# SC2086: Disable double quote expansion.

set -eu

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 (local|oss)"
  exit 1
fi

PLATFORM=
if [ "$(uname -m)" == "arm64" ]; then
  echo "Building for ARM64"
  PLATFORM="--platform linux/amd64"
fi

docker build ${PLATFORM} -t pivotal-cf-onboarding .
docker run ${PLATFORM} -v "$PWD:/onboarding" -w /onboarding pivotal-cf-onboarding go run generate-tracker-csv.go "${1}"

echo -e "\n\nGenerated output CSV at '$PWD/onboarding-tracker.csv'"
